swagger: "2.0"
info:
  title: Pokemon API
  description: API for getting Pokemon information
  version: "1.0.0"
host: "localhost:8080"
basePath: "/"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pokemon/{id}:
    get:
      summary: Retrieve a Pokemon by ID
      description: Returns a Pokemon by ID
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the Pokemon to retrieve
          required: true
          type: string
          default: ditto
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/PokemonResponse"
        "400":
          description: Bad request
        "404":
          description: Pokemon not found
        "500":
          description: Internal server error
definitions:
  PokemonResponse:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: "bulbasaur"
      types:
        type: array
        items:
          $ref: "#/definitions/PokemonType"
      stats:
        type: array
        items:
          $ref: "#/definitions/PokemonStat"
  PokemonType:
    type: object
    properties:
      slot:
        type: integer
        example: 1
      type:
        $ref: "#/definitions/BaseName"
  PokemonStat:
    type: object
    properties:
      base_stat:
        type: integer
        example: 45
      stat:
        $ref: "#/definitions/BaseName"
  BaseName:
    type: object
    properties:
      name:
        type: string
        example: "grass"
