swagger: "2.0"
info:
  title: Pokemon API
  description: API for getting Pokemon information
  version: "1.0.0"
host: "localhost:8080"
basePath: "/"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pokemon/{id}:
    get:
      summary: Retrieve a Pokemon by ID or name
      description: Returns a Pokemon by ID or name
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID or name of the Pokemon to retrieve
          required: true
          type: string
          default: ditto
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/Pokemon"
        "400":
          description: Bad request
        "404":
          description: Pokemon not found
        "500":
          description: Internal server error
definitions:
  Pokemon:
    type: object
    properties:
      id:
        type: integer
        example: 132
      name:
        type: string
        example: "ditto"
      type:
        type: string
        example: "normal"
      abilities:
        type: object
        example: { "attack": 48, "defense": 48, "hp": 48, "speed": 48 }
        additionalProperties:
          type: integer
